[tool.poetry]
name = "rsserpent-plugin-example"
version = "0.0.0"
description = "An example plugin for RSSerpent ğŸ"
authors = ["Queensferry <queensferry.me@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pyquery = "^1.4.3"
requests = "^2.25.1"
rsserpent = "^0.1.0-alpha.4"

[tool.poetry.dev-dependencies]
fastapi = "^0.65.2"
pre-commit = "^2.13.0"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"

[tool.black]
include = '\.pyi?$'
target-version = ["py37", "py38", "py39"]

[tool.isort]
balanced_wrapping = true
combine_as_imports = true
lines_after_imports = 2
profile = "black"

[tool.poetry.plugins."rsserpent.plugins"]
"example" = "rsserpent_plugin_example:plugin"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
